{
  "swagger" : "2.0",
  "info" : {
    "description" : "dbAPI",
    "version" : "v1",
    "title" : "dbapi",
    "termsOfService" : "https://developer.db.com/#/termsandconditions",
    "contact" : {
      "url" : "https://developer.db.com/#/support",
      "email" : "bank.api@db.com"
    }
  },
  "host" : "simulator-api.db.com:443",
  "basePath" : "/gw/dbapi",
  "tags" : [ {
    "name" : "Addresses"
  }, {
    "name" : "Cash Accounts"
  }, {
    "name" : "Processing Orders"
  }, {
    "name" : "Transactions"
  }, {
    "name" : "Partners"
  }, {
    "name" : "Age Certificate"
  }, {
    "name" : "Customer Solvency"
  }, {
    "name" : "Transaction Certificate"
  } ],
  "schemes" : [ "https" ],
  "paths" : {
    "/v1/addresses" : {
      "get" : {
        "tags" : [ "Addresses" ],
        "summary" : "Reads all addresses of the current user.",
        "description" : "Reads all addresses of the current user. There might be several private and business addresses. AddressType can be BUSINESS_ADDRESS or PRIVATE_ADDRESS. Country format is ISO code.",
        "operationId" : "getAddresses",
        "security" : [ {
          "api_auth_code" : [ "read_addresses" ]
        }, {
          "api_implicit" : [ "read_addresses" ]
        } ]
      }
    },
    "/v2/addresses" : {
      "get" : {
        "tags" : [ "Addresses" ],
        "summary" : "Reads all addresses of the current user.",
        "description" : "Reads all addresses of the current user. There might be several private and business addresses. AddressType can be BUSINESS_ADDRESS or PRIVATE_ADDRESS. Country format is ISO code.",
        "operationId" : "getAddressesV2",
        "security" : [ {
          "api_auth_code" : [ "read_addresses" ]
        }, {
          "api_implicit" : [ "read_addresses" ]
        } ]
      }
    },
    "/v1/cashAccounts" : {
      "get" : {
        "tags" : [ "Cash Accounts" ],
        "summary" : "Reads all cash accounts of the current user.",
        "description" : "Reads all cash accounts of the current user. Only current accounts and accounts in the currency EUR are returned. If given IBAN is not valid or does not represent an account of the current user, an empty result is returned.",
        "operationId" : "getCashAccounts",
        "security" : [ {
          "api_auth_code" : [ "read_accounts" ]
        }, {
          "api_implicit" : [ "read_accounts" ]
        } ]
      }
    },
    "/v2/cashAccounts" : {
      "get" : {
        "tags" : [ "Cash Accounts" ],
        "summary" : "Reads all cash accounts of the current user.",
        "description" : "Reads all cash accounts of the current user. Only current accounts and accounts in the currency EUR are returned. If given IBAN is not valid or does not represent an account of the current user, an empty result is returned.",
        "operationId" : "getCashAccountsV2",
        "security" : [ {
          "api_auth_code" : [ "read_accounts" ]
        }, {
          "api_implicit" : [ "read_accounts" ]
        } ]
      }
    },
    "/v1/processingOrders" : {
      "post" : {
        "tags" : [ "Processing Orders" ],
        "summary" : "Create a processing order",
        "description" : "Create a processing order. This endpoint has limited access for special consumers only. It’s possible to start manual processes only.",
        "operationId" : "createProcessingOrders",
        "security" : [ {
          "api_client_credential" : [ "create_processing_orders" ]
        } ]
      }
    },
    "/v1/transactions" : {
      "get" : {
        "tags" : [ "Transactions" ],
        "summary" : "Reads all transactions of the current cash account.",
        "description" : "Reads all transactions for a specific account of the current user. If given IBAN is not valid or does not represent an account of the current user, an empty result is returned. It is not apparent who issued a transaction, only whether the user gained or lost money by it (based on whether the amount is positive or negative respectively). The maximum number of transactions returned is 200.",
        "operationId" : "getCashAccountTransactions",
        "security" : [ {
          "api_implicit" : [ "read_transactions" ]
        }, {
          "api_auth_code" : [ "read_transactions" ]
        } ]
      }
    },
    "/v2/transactions" : {
      "get" : {
        "tags" : [ "Transactions" ],
        "summary" : "Reads all transactions of the current cash account.",
        "description" : "Reads all transactions for a specific account of the current user. If given IBAN is not valid or does not represent an account of the current user, an empty result is returned. It is not apparent who issued a transaction, only whether the user gained or lost money by it (based on whether the amount is positive or negative respectively). The maximum number of transactions returned is 200.",
        "operationId" : "getCashAccountTransactionsV2",
        "security" : [ {
          "api_implicit" : [ "read_transactions" ]
        }, {
          "api_auth_code" : [ "read_transactions" ]
        } ]
      }
    },
    "/v1/partners" : {
      "get" : {
        "tags" : [ "Partners" ],
        "summary" : "Retrieves personal information about the current partner.",
        "description" : "Retrieves personal information (e.g. first name, last name, date of birth) about the current partner.",
        "operationId" : "getPartners",
        "security" : [ {
          "api_auth_code" : [ "read_partners", "read_partners_legi" ]
        }, {
          "api_implicit" : [ "read_partners", "read_partners_legi" ]
        } ]
      }
    },
    "/v2/partners" : {
      "get" : {
        "tags" : [ "Partners" ],
        "summary" : "Retrieves personal information about the current partner.",
        "description" : "Retrieves personal information (e.g. first name, last name, date of birth) about the current partner.",
        "operationId" : "getPartnersV2",
        "security" : [ {
          "api_auth_code" : [ "read_partners", "read_partners_legi" ]
        }, {
          "api_implicit" : [ "read_partners", "read_partners_legi" ]
        } ]
      }
    },
    "/v1/ageCertificate" : {
      "get" : {
        "tags" : [ "Age Certificate" ],
        "summary" : "Age Certificate",
        "description" : "'AgeCertificate' validates whether your Deutsche Bank customer is compliant with given age restrictions - based on the bank's records. Please note: This endpoint is currently only available in our APIs simulator stack and ready for you to test it. Don't hesitate to submit us your feedback and stay tuned on our future product development.",
        "operationId" : "ageCertificate",
        "security" : [ {
          "api_auth_code" : [ "read_partners" ]
        }, {
          "api_implicit" : [ "read_partners" ]
        } ]
      }
    },
    "/v1/customerSolvency" : {
      "get" : {
        "tags" : [ "Customer Solvency" ],
        "summary" : "Checks the solvency for the current customer for a given account.",
        "description" : "CustomerSolvency does the background check of a customer’s creditworthiness based on past transactions and account data. A score of solvency is returned, providing you with more security that your customer is likely to pay his bill. Please note: This endpoint is currently only available in our APIs simulator stack and ready for you to test it. Don't hesitate to submit us your feedback and stay tuned on our future product development.",
        "operationId" : "getSolvency",
        "security" : [ {
          "api_auth_code" : [ "read_transactions" ]
        }, {
          "api_implicit" : [ "read_transactions" ]
        } ]
      }
    },
    "/v1/transactionCertificate" : {
      "get" : {
        "tags" : [ "Transaction Certificate" ],
        "summary" : "Transaction Certificate",
        "description" : "Signing new contracts such as a lease contract often require the customer to provide a salary certificate from their bank. Getting hold of such a proof can be time consuming and annoying. TransactionCertificate automates this process and provides all the necessary data instantly. All parties save time on concluding contracts. Please note: This endpoint is currently only available in our APIs simulator stack and ready for you to test it. Don't hesitate to submit us your f[...]",
        "operationId" : "transactionCertificate",
        "security" : [ {
          "api_auth_code" : [ "read_transactions" ]
        }, {
          "api_implicit" : [ "read_transactions" ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "api_auth_code" : {
      "type" : "oauth2",
      "authorizationUrl" : "https://simulator-api.db.com:443/gw/oidc/authorize",
      "tokenUrl" : "https://simulator-api.db.com:443/gw/oidc/token",
      "flow" : "accessCode",
      "scopes" : {
        "read_accounts" : "Read your accounts",
        "read_transactions" : "Read your transactions",
        "read_partners" : "Read your personal info",
        "read_partners_legi" : "Read your personal legitimation info",
        "read_addresses" : "Read your addresses",
        "openid" : "Request access to OpenId Connect functionality",
        "offline_access" : "Request an OAuth2 Refresh Token"
      }
    },
    "api_client_credential" : {
      "type" : "oauth2",
      "tokenUrl" : "https://simulator-api.db.com:443/gw/oidc/token",
      "flow" : "application",
      "scopes" : {
        "create_processing_orders" : "Create processing orders"
      }
    },
    "api_implicit" : {
      "type" : "oauth2",
      "authorizationUrl" : "https://simulator-api.db.com:443/gw/oidc/authorize",
      "flow" : "implicit",
      "scopes" : {
        "read_accounts" : "Read your accounts",
        "read_transactions" : "Read your transactions",
        "read_partners" : "Read your personal info",
        "read_partners_legi" : "Read your personal legitimation info",
        "read_addresses" : "Read your addresses",
        "openid" : "Request access to OpenId Connect functionality"
      }
    }
  }
}
